### ISSUE TITLE
Gathering Records : File Uploads Issues - Backend Exceptions - Conversion in progress always!!

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3604]
**Describe the bug in current situation**

During the Upload of certain files refer files Bug #3603, there are few exceptions on `DEDUPE` and `REQUEST MANAGEMENT API` - Need to analyze why this happens and if relevant need to handle , else comment.

Also, this is can be related to this, On the below Requests on DEV- Marshal, File Conversion process is always in progress

https://dev-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/ministryreview/537/ministryrequest/539
https://dev-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/ministryreview/539/ministryrequest/541

**REQUEST MANAGEMENT API EXCEPTION** 
`  records changed == {'recordchanged': False}
records changed == {'recordchanged': False}
getpdfstichstatus result ==
records changed == {'recordchanged': False}
[2023-04-06 22:52:20,726] ERROR (request_api) <app.py:app.py:1455>.log_exception: Exception on /api/foirecord/538/ministryrequest/540 [POST]
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/usr/local/lib/python3.8/site-packages/flask_restx/api.py", line 404, in wrapper
resp = resource(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 84, in view
return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flask_restx/resource.py", line 46, in dispatch_request
resp = meth(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flask_opentracing/tracing.py", line 82, in wrapper
r = f(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
resp = make_response(f(*args, **kwargs))
File "/usr/local/lib/python3.8/site-packages/flask_jwt_oidc/jwt_manager.py", line 272, in decorated
return f(*args, **kwargs)
File "/app/request_api/auth.py", line 41, in decorated
return f(*args, **kwargs)
File "/app/request_api/resources/foirecord.py", line 66, in post
recordschema = FOIRequestBulkCreateRecordSchema().load(requestjson)
File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 699, in load
return self._do_load(
File "/usr/local/lib/python3.8/site-packages/marshmallow/schema.py", line 865, in _do_load
raise exc
marshmallow.exceptions.ValidationError: {'records': {3: {'filename': ['Field exceeds the size limit']}}}`

######################################################

DEDUPE EXCEPTIONS

` processing b'1680820770694-0'::{b's3filepath': b'https://citz-foi-prod.objectstore.gov.bc.ca/edu-dev-e/EDU-2023-06041453/a4ce02fe-b497-4413-a126-db223022a581.pdf', b'requestnumber': b'EDU-2023-06041453', b'bcgovcode': b'EDU', b'filename': b'nanmvc-nnmsfv-eng.doc', b'ministryrequestid': b'539', b'attributes': b'{"filesize": 507904, "divisions": [{"divisionid": 2}], "batch": "0ea91662-5e24-4add-bd4e-f4c4539d8fea", "extension": ".doc", "incompatible": false}', b'batch': b'0ea91662-5e24-4add-bd4e-f4c4539d8fea', b'jobid': b'8347', b'documentmasterid': b'8734', b'outputdocumentmasterid': b'8741', b'trigger': b'recordupload', b'createdby': b'foiedu@idir'}
duplicate key value violates unique constraint "DeduplicationJob_pkey"
DETAIL: Key (deduplicationjobid, version)=(8347, 2) already exists.
ERROR:root:duplicate key value violates unique constraint "DeduplicationJob_pkey"
DETAIL: Key (deduplicationjobid, version)=(8347, 2) already exists.
Traceback (most recent call last):
File "/home/app_user/services/foiredisdedupeconsumer.py", line 56, in start
processmessage(producermessage)
File "/home/app_user/services/dedupeservice.py", line 8, in processmessage
recordjobstart(message)
File "/home/app_user/services/dedupedbservice.py", line 37, in recordjobstart
cursor.execute('''INSERT INTO public."DeduplicationJob"
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "DeduplicationJob_pkey"
DETAIL: Key (deduplicationjobid, version)=(8347, 2) already exists.`

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to ** https://dev-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/ministryreview/537/ministryrequest/539
https://dev-marshal-foirequest.apps.silver.devops.gov.bc.ca/foi/ministryreview/539/ministryrequest/541 **

2. Click on GATHERING RECORDS
3. See the documents in process !! Its uploaded on Apr 06, between 3:30 and 4:14

Refer the files uploaded on [https://app.zenhub.com/files/358004325/f716bfc5-b220-41b7-95a9-2feecda0055b/download](https://app.zenhub.com/files/358004325/f716bfc5-b220-41b7-95a9-2feecda0055b/download)

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by sumathi-thirumani-aot** [comment]
The filename length issue is changed to support the length of 500 characters. The change is moved to dev-marshal.
