### ISSUE TITLE
Conversion POD restarted  with very low load - Unknown issue?

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#3732]
**Describe the bug in current situation**

The conversion service got restarted all of a sudden. 

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/1d7eacaf-8abb-44fd-aaf7-9cb3de34e1e4)

![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/0f80a3e4-3dec-4016-808e-c27316cbc698)
**Link bug to the User Story**

**Impact of this bug**

Info from @divyav-aot log

Error happpened while running the FOI File Conversion service. Exception message : NOGROUP No such key 'file-conversion' or consumer group 'test' in XREADGROUP with GROUP option , StackTrace :   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1895

April 28th 2023, 12:54:05.453
reviewer-conversion

   at StackExchange.Redis.RedisDatabase.StreamReadGroup(RedisKey key, RedisValue groupName, RedisValue consumerName, Nullable1 position, Nullable1 count, Boolean noAck, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2764
https://kibana-openshift-logging.apps.silver.devops.gov.bc.ca/app/kibana#/discover?_g=(time:(from:now-1w,mode:relative,to:now))&_a=(columns:!(kubernetes.container_name,message),index:ce599300-e3c6-11ed-a1ab-696655fe8615,interval:auto,query:(language:lucene,query:(query_string:(analyze_wildcard:!t,query:'kubernetes.pod_name:%22reviewer-conversion-75-4c6cd%22%20AND%20kubernetes.namespace_name:%22d106d6-test%22%20AND%20kubernetes.container_name.raw:%22reviewer-conversion%22'))),sort:!('@timestamp',desc))

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
Cannot be reproduced OR we have solved this as part of other load testing
