### ISSUE TITLE
Receipt Attachment missing on the FOI INTAKE SUBMISSION email and end user confirmation email

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4572]
**Describe the bug in current situation**
Arielle from Intake team has reported like, the receipt attachments are missing  on some  FOI REQUEST submission emails . 

Upon analysis its observed that there is a `504 Gateway Timeout` happening with  NODE BE logic on FOI SUBMISSION APP, while calling receipt generation endpoint on request management api( FOI FLOW) side. 
`
---submitFoiRequestEmail Generate Receipt Error starts--
{ Error: Request failed with status code 504
    at createError (/opt/app-root/src/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/app-root/src/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/app-root/src/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { url:
      'https://request-management-api-002-prod.apps.silver.devops.gov.bc.ca/api/foirawrequests/15454/payments/4579/receipt',
     method: 'post', 
  toJSON: [Function: toJSON] }
---submitFoiRequestEmail Generate Receipt Error ends--
`
 Error can be related with  CDOGS Service is taking more time to generate PDF which in turn makes a timeout on Angular app, NODE Backend. 

**Link bug to the User Story**

**Impact of this bug**
 No loss of information related to payment, since we convey TRANSACTION# on email message as well. Breakdown of total is missing and order id will be missing - that is only on receipt. We don't know  whether this was happening before OCT 5th, since we recreated PODS on OCT 5th.

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
There is specific reproduction steps, sporadic in nature! As per logs, it happened 2 times - between OCT 5 and OCT 6 evening.

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by abin-aot** [comment]
Issue with CDOGS systems due to other client's over usage. More details here, https://chat.developer.gov.bc.ca/channel/nr-common-services-showcase/thread/35Hhk9LvSBMTdC7DP
